8 listado de items chips alergenos
la-true-liga/mercatech-ng-frontal pull request #9
Opened 2023-10-22 18:42 UTC by 42Alberto

Se necesitan dos aprobaciones y solo está Ale pa aprobar, no entiendo

2023-10-23 17:24 UTC, jdomingu98 requested changes
cambia la regla de los punto y coma ninio

2023-10-23 17:34 UTC, ruzafa8 commented
Cuando me ponga el próximo día lo subimos en un commit en esta misma PR, o si @42Alberto quiere investigar como se quita, que lo haga cuando pueda

2023-10-23 17:46 UTC, ruzafa8 approved these changes
Lo veo bien, solo te dejé unos comentarios más bien de prácticas buenas para que quede elegante :)
Otra cosa que vi es que lo suyo es poner nombres de funciones, variables y comentarios en inglés, pero si prefieres en español por aclararte las cosas, no te dejaré comentarios de "es buena práctica poner esto en inglés".

2023-10-23 17:46 UTC, ruzafa8 commented on src/app/tab2/tab2.page.html
> +        <!--<app-chip-item></app-chip-item>-->
recomendable quitar comentarios si no es necesario

2023-10-23 17:46 UTC, ruzafa8 commented on src/app/tab2/tab2.page.ts
> +    console.log('Nuevo valor de searchQuery:', this.searchQuery);
recomendable no subir console log

2023-10-23 17:46 UTC, ruzafa8 commented on src/app/tab2/tab2.page.html
> +      List
El próximo día vemos cosillas de literales de traducción

2023-10-23 17:46 UTC, ruzafa8 commented on src/app/list-item/list-item.component.ts
> +  ngOnInit() {}
si ngOnInit está vacío no es necesario ponerlo (no es necesario hacer el implements OnInit). Lo mismo el constructor

2023-10-23 17:46 UTC, ruzafa8 commented on package.json
> +    "@angular/material": "^16.2.8",
Al final creo que no estamos usando material en esta PR. Lo mantenemos por si lo usamos más a futuro?
He pensado que no renta tener ionic y material por unificar estilos, pero si quieres tenerlo pa que rente y jugar con ambas librerías, palante

2023-10-23 17:54 UTC, ruzafa8 commented
> Se necesitan dos aprobaciones y solo está Ale pa aprobar, no entiendo

Estaré yo como obligatorio, mas una aprobación random de quien quiera

2023-10-24 06:13 UTC, 42Alberto commented on src/app/list-item/list-item.component.ts
> +  ngOnInit() {}
Pero cuando creo un componente me lo pone de base, no sabia que hacer con ello q.q

2023-10-24 06:14 UTC, 42Alberto commented on package.json
> +    "@angular/material": "^16.2.8",
No, no renta, pero me daba errores de que no encontraba cosas de material y no lograba quitarlo asi que decidí instalarlo de nuevo, este sábado lo vemos

2023-10-26 15:53 UTC, ruzafa8 commented on src/app/list-item/list-item.component.ts
> +  ngOnInit() {}
ya, lo pone por defecto. Pero no pasa na, se puede quitar y funciona todo perfecto :smile:

2023-10-27 18:12 UTC, jdomingu98 approved these changes
venga va te lo dejo pasar

2023-10-27 18:53 UTC, merged